#!/usr/bin/env python3
"""
strip_torch_from_lock.py
========================
Remove torch and its CUDA/transitive deps from a pip-compile lockfile, then
prepend a comment header. Invoked by ``make lockfile``.

Torch is omitted because the wheel index (CPU vs CUDA) is installer-dependent;
``setup.sh`` installs it separately from ``https://download.pytorch.org/whl/cpu``.

Usage
-----
    python scripts/strip_torch_from_lock.py requirements-lock.txt
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PKGS_TO_STRIP = {"torch", "triton", "fsspec", "networkx", "sympy", "mpmath"}

HEADER = """# requirements-lock.txt — pinned versions for reproducible installs.
#
# Generated by pip-compile (pip-tools) from pyproject.toml. Covers the base
# dependencies plus the [dev], [docs], and [notebook] extras.
#
# PyTorch is intentionally NOT pinned here because the wheel index is
# platform-specific (CPU vs CUDA). Install torch separately via setup.sh
# or with:
#     pip install "torch>=2.4.0" --index-url https://download.pytorch.org/whl/cpu
#
# Regenerate with:
#     make lockfile        # invokes pip-compile + this post-processing
#
# pyproject.toml remains the source of truth for version ranges; this file
# pins exact versions for CI / prod.

"""


def strip(path: Path) -> None:
    lines = path.read_text().splitlines(keepends=True)

    # Drop multi-line package blocks whose head matches an unwanted package.
    kept = []
    i = 0
    while i < len(lines):
        line = lines[i]
        m = re.match(r"^([a-z0-9][a-z0-9\-_.]+)==", line, re.IGNORECASE)
        if m:
            pkg = m.group(1).lower()
            if pkg in PKGS_TO_STRIP or pkg.startswith("nvidia"):
                i += 1
                while i < len(lines) and lines[i].startswith(" "):
                    i += 1
                continue
        kept.append(line)
        i += 1

    # Drop "# via <stripped-pkg>" trailers inside other packages' via lists.
    trailer_pattern = re.compile(
        r"^\s+#(\s+via)?\s+(" + "|".join(PKGS_TO_STRIP | {"nvidia[-a-z0-9]*"}) + r")\s*$"
    )
    cleaned = [ln for ln in kept if not trailer_pattern.match(ln.rstrip())]

    # Strip pip-compile's own header; replace with ours.
    body = "".join(cleaned)
    body = re.sub(r"^(#[^\n]*\n|\s*\n)+", "", body, count=1)
    path.write_text(HEADER + body)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    strip(Path(sys.argv[1]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
